#!/bin/sh

# Symlink the config files to home
ln -sf "$PWD/bashrc" "$HOME/.bashrc"
ls -lh "$HOME/.bashrc"

ln -sf "$PWD/bash_profile" "$HOME/.bash_profile"
ls -lh "$HOME/.bash_profile"

# ln -sf "$PWD/dircolors" "$HOME/.dircolors"
# ls -lh "$HOME/.dircolors"

ln -sf "$PWD/vimrc" "$HOME/.vimrc"
ls -lh "$HOME/.vimrc"

ln -sf "$PWD/tmux.conf" "$HOME/.tmux.conf"
ls -lh "$HOME/.tmux.conf"

# Downlad dictionaries for vim spell check
wget -P ~/.vim/spell/ http://ftp.vim.org/vim/runtime/spell/de.utf-8.spl
wget -P ~/.vim/spell/ http://ftp.vim.org/vim/runtime/spell/de.utf-8.sug

# Install the Plug plugin manager for vim
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install some packages
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y remove vim-tiny
sudo apt-get -y install xclip tmux vim-gtk3 lynx w3m make build-essential curl shellcheck git synaptic aria2 neofetch p7zip-full unrar-free unace tree python3 python3-pip
sudo apt-get -y install vlc mpv ffmpeg ffmpegthumbnailer gwenview
sudo apt-get -y install pandoc texlive-latex-base texlive-fonts-recommended texlive-lang-german texlive-lang-english
sudo apt-get -y install hunspell hunspell-de-de-frami hunspell-de-med hunspell-en-gb hunspell-en-us hunspell-en-med
sudo apt-get -y install tldr && tldr --update
