#!/bin/sh

set -e  # Exit immediately if a command exits with a non-zero status.

touch "connection-ping.log"
ping -i 3 'google.com' | xargs -I '{}' date '+%Y-%m-%d %H:%M:%S  {}' | tee -a 'connection-ping.log'
