#!/bin/bash

set -e  # Exit immediately if a command exits with a non-zero status.

# This would be for renaming all files in a directory
# for file in *; do mv "$file" $(echo $file | tr ' ' '-') ; done
if test -f "$1"; then
  mv "$1" "$(printf "%s" "$1" | tr ' ' '-')"
fi
