#!/bin/sh

set -e  # Exit immediately if a command exits with a non-zero status.

# This searches recursively in the zet folder
# for the search term in all .md files
grep -RIiHn --color=auto --include=*.md "$*" "$ZETTEL"